# Generated by Django 2.2.6 on 2019-10-28 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='neighbourhood_description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='neighbourhood',
            new_name='neighbourhood_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('business_hood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biz', to='watch.Neighbourhood')),
                ('business_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
