# Generated by Django 2.2.6 on 2019-10-28 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watch', '0002_auto_20191028_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='neighbourhood',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='locality',
            field=models.CharField(default='e.g Nairobi, Thika, Ruiru etc', max_length=30),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(default='Name', max_length=30),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='occupants_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='user_profile',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hoods', to=settings.AUTH_USER_MODEL),
        ),
    ]
