# Generated by Django 2.2.6 on 2019-10-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_auto_20191025_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='neighbourhood_description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='neighbourhood',
            new_name='neighbourhood_name',
        ),
    ]
