# Generated by Django 2.2.6 on 2019-10-28 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_auto_20191028_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
