# Generated by Django 2.2.6 on 2019-10-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
