# Generated by Django 2.2.6 on 2019-10-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0007_auto_20191029_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='locality',
            field=models.CharField(max_length=30),
        ),
    ]
